name: TeamViewer Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download TeamViewer
        run: |
          Invoke-WebRequest -Uri "https://download.teamviewer.com/download/TeamViewer_Setup.exe" -OutFile "TeamViewer_Setup.exe"
          Start-Process -FilePath "TeamViewer_Setup.exe" -ArgumentList "/S /Q"
      - name: Retrieve ID and password
        run: |
          $teamViewerID = Get-WmiObject Win32_Product | Where-Object {$_.Name -like "*TeamViewer*"} | Select-Object -ExpandProperty IdentifyingNumber
          $teamViewerPassword = (Get-Content -Path "C:\Program Files (x86)\TeamViewer\Connections_incoming.txt" -TotalCount 1).Split("=")[1].Trim()
          echo "TeamViewer ID: $teamViewerID"
          echo "TeamViewer Password: $teamViewerPassword"
